"""Generate an Algorand testnet wallet.

Run once, then save the address + mnemonic in backend/.env.
The mnemonic is the wallet keys (25 words). Anyone with it can drain the wallet.
Do not commit it to GitHub.

Usage:
  python generate_wallet.py          # prints address + mnemonic
  python generate_wallet.py --write  # also writes them to backend/.env
"""

import argparse
from pathlib import Path

from algosdk import account, mnemonic


def main(write_env: bool) -> None:
    private_key, address = account.generate_account()
    mn = mnemonic.from_private_key(private_key)

    print(f"Address:  {address}")
    print(f"Mnemonic: {mn}")
    print("\nSave these in backend/.env NOW")
    print("NEVER commit the mnemonic to GitHub")

    if write_env:
        env_path = Path(__file__).resolve().parents[1] / ".env"
        env_path.parent.mkdir(parents=True, exist_ok=True)

        env_content = (
            "# Generated by generate_wallet.py\n"
            "# WARNING: This file contains your mnemonic. Do NOT commit it.\n\n"
            f"ALGO_MNEMONIC={mn}\n"
            f"ALGO_ADDRESS={address}\n"
            "ALGO_NETWORK=testnet\n"
        )

        env_path.write_text(env_content, encoding="utf-8")
        print(f"\nWrote wallet info to: {env_path}")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Generate an Algorand testnet wallet.")
    parser.add_argument(
        "--write",
        action="store_true",
        help="Write the generated address+mnemonic into backend/.env",
    )
    args = parser.parse_args()

    main(write_env=args.write)
